name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository with LFS
      uses: actions/checkout@v2
      with:
        lfs: true   # <-- ensure LFS files are pulled

    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_macos.universal.zip
        unzip Godot_v4.3-stable_macos.universal.zip -d godot
        sudo mv godot/Godot.app /Applications/Godot.app
        sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot

    - name: Download Godot Export Templates
      run: |
        mkdir -p ~/Library/Application\ Support/Godot/templates/4.3-stable
        cd ~/Library/Application\ Support/Godot/templates/4.3-stable
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        tar -xzf Godot_v4.3-stable_export_templates.tpz -C ~/Library/Application\ Support/Godot/templates/4.3-stable
        cd templates
        mv * ..
        cd ..
        ls

    - name: Create build directory
      run: mkdir -p build

    - name: Export iOS project
      run: godot --export-debug "iOS" build/yks.xcodeproj
      env:
        DISPLAY: :99.0
        
    - name: Set iOS Deployment Target
      run: sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' build/yks.xcodeproj/project.pbxproj

    - name: Build iOS project
      run: xcodebuild -project build/yks.xcodeproj -scheme yks -configuration Development -archivePath build/yks.xcarchive archive \ CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: | 
        cd build
        cd yks.xcarchive
        cd Products
        cd Applications
        mkdir Payload
        mv yks.app Payload/
        zip -r App.ipa Payload/
        mv App.ipa ../../../

    - name: Upload IPA to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ipa
        path: build/App.ipa
